---
title: "Survival Analysis HW 1"
author: "Jackson Cabell"
date: "11/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(survminer)
library(tidyverse)
library(ggplot2)
library(haven)
library(dplyr)
```

# Calculate summary statistics for each type of pump station failure
```{r}
hurricane <- read_sas("hurricane.sas7bdat")

# Calculate the % of pumps which survived the hurricane
mean(hurricane$survive)
hurricane_fail <- hurricane %>% filter(reason !=0)

# Calculate % of pumps in each type of failure and average failure time for each failure type
# Hour gives time of failure
pump_summary <- hurricane_fail %>%
                group_by(reason) %>%
                summarize(
                  proportion = n()/nrow(hurricane_fail),
                  avg_failure = mean(hour),
                  med_failure = median(hour)
                )
pump_summary

# Test difference of measn globally between means
#exclude censored
hurricane_fail <- hurricane %>% filter(reason !=0)
aov_pump <- aov(hurricane_fail$hour ~ factor(hurricane_fail$reason))
summary(aov_pump) #Results in significant p-value: so the mean times are different

#Ad-hoc tukey pairwise comparison
tukey <- TukeyHSD(aov_pump)
plot(tukey)

#Means doesn't make sense- check boxplots
ggplot(hurricane_fail) +
  geom_boxplot(aes(y=hour, color = factor(reason))) + theme_classic() +
  labs(color="Reason", y ="Failure Hour")

```

# Create requested graphs

```{r}
#Survival probability across time for all pumps together - not broken down by failure type
surv <- Surv(time = hurricane$hour, event = hurricane$survive == 0)
surv_full <- survfit(surv ~ 1, data = hurricane) #surv_full$surv gets survival prob and $time gets hours
plot(surv_full, main = "Survival Function", xlab = "Hours", ylab = "Survival Probability", conf.int=FALSE)

# Survival probaility for all pumpes broken down by failure type overlaid into one graph
hurr_strat <- survfit(Surv(time = hurricane_fail$hour, event = hurricane_fail$survive == 0) ~ reason,
                      data = hurricane_fail)


ggsurvplot(hurr_strat, data = hurricane_fail, conf.int = FALSE, palette = c("black", "red", "blue", "brown"),
           xlab = "Week", ylab = "Survival Probability", break.y.by = 0.1,
           legend.title = "Reason", legend.labs = c("Flood", "Motor", "Surged", "Jammed"))

#Conditional failure probabilities across time for all pumps together - not broken down by failure type
# Calculate hz probs
surv_full$hp <- surv_full$n.event/surv_full$n.risk
hurr_haz <- merge(data.frame(time = seq(1,48,1)), data.frame(time = surv_full$time, hp = surv_full$hp),
                    by = "time", all = TRUE)
hurr_haz[is.na(hurr_haz) == TRUE] <- 0

plot(y = hurr_haz$hp, x = hurr_haz$time, main = "Hazard Probability Function",
     xlab = "Hours", ylab = "Hazard Probability", type = 'l')


# Conditional failure probabilities across time for pumps broken down by failure type overlaid onto one graph
# Calculate hz probs
hurr_strat$hp <- hurr_strat$n.event/hurr_strat$n.risk
hurr_haz <- merge(data.frame(time = c(seq(1,48,1),seq(1,48,1), seq(1,48,1), seq(1,48,1)),
                             reason = c(rep("reason=1", 48), rep("reason=2", 48),
                                        rep("reason=3", 48), rep("reason=4", 48))),
                  data.frame(time = hurr_strat$time, hp = hurr_strat$hp, reason = summary(hurr_strat)$strata),
                    by = c("time", "reason"), all = TRUE) %>%
            mutate(reason = ifelse(reason=="reason=1", 1,
                                   ifelse(reason=="reason=2", 2,
                                          ifelse(reason=="reason=3", 3,4))))
hurr_haz[is.na(hurr_haz) == TRUE] <- 0

ggplot(hurr_haz) +
  geom_line(aes(x=time, y=hp, color = factor(reason))) + theme_classic() +
  labs(color="Reason", y ="Hazard Probability", x = "Hour")

```

# Test survival probabilities

```{r}
# 1 = Flood
# 2 = Motor
# 3 = Surge
# 4 = Jammed

#Survival probaility for all pumps Wilcoxon (1 & 2) Flood and Motor
short <- hurricane_fail %>% filter(reason %in% c(1,2))
surv_fail <- Surv(time = short$hour, event = short$survive == 0)
survdiff(surv_fail ~ reason, rho = 1, data = short)

# Survival probaility for all pumps Wilcoxon (1 & 3) Flood and Surge
short <- hurricane_fail %>% filter(reason %in% c(1,3))
surv_fail <- Surv(time = short$hour, event = short$survive == 0)
survdiff(surv_fail ~ reason, rho = 1, data = short)

# Survival probaility for all pumps Wilcoxon (1 & 4) Flood and Jammed
short <- hurricane_fail %>% filter(reason %in% c(1,4))
surv_fail <- Surv(time = short$hour, event = short$survive == 0)
survdiff(surv_fail ~ reason, rho = 1, data = short)

# Survival probaility for all pumps Wilcoxon (2 & 3) Motor and Surged
short <- hurricane_fail %>% filter(reason %in% c(2,3))
surv_fail <- Surv(time = short$hour, event = short$survive == 0)
survdiff(surv_fail ~ reason, rho = 1, data = short)

# Survival probaility for all pumps Wilcoxon (2 & 4) Motor and Jammed
short <- hurricane_fail %>% filter(reason %in% c(2,4))
surv_fail <- Surv(time = short$hour, event = short$survive == 0)
survdiff(surv_fail ~ reason, rho = 1, data = short)

# Survival probaility for all pumps Wilcoxon (3 & 4) Surge and Jammed
short <- hurricane_fail %>% filter(reason %in% c(3,4))
surv_fail <- Surv(time = short$hour, event = short$survive == 0)
survdiff(surv_fail ~ reason, rho = 1, data = short)



# Create column for major failure type groupings ("Water-based" (1,3) and "Mechanical" (2,4))
hurricane_fail <- hurricane_fail %>%
                  mutate (group = ifelse(reason %in% c(2,3), "Motor-Surged", "Flood-Jammed"))


# Stratified Analysis test- logrank comparing Water-Based and Mechanical
surv_fail <- Surv(time = hurricane_fail$hour, event = hurricane_fail$survive == 0)
survdiff(surv_fail ~ group, rho = 1, data = hurricane_fail) #p= 1 

# Plot survival curve
hurr_strat <- survfit(surv_fail ~ group, data = hurricane_fail)
ggsurvplot(hurr_strat, data = hurricane_fail, conf.int = FALSE, palette = c("black", "red"),
           xlab = "Hours", ylab = "Survival Probability", break.y.by = 0.1,
           legend.title = "Reason", legend.labs = c("Flood-Jammed", "Motor-Surged"))

```
